### PR TITLE
Fixes Mouse Pointer theme in app snap

### PR DESCRIPTION
**Pull request by keshavbhatt**
recipe to fix mouse cursor theme issue if the application installed using snap packaging format.

### CODE REVIEW

**Comment by kraxarn** [comment]
Thank you!
Were you able to properly test this without the snap version building?

**Comment by kraxarn** [comment]
Sounds good to me :relaxed:

**Comment by kraxarn** [comment]
Reverting this as it causes validation errors:
```
unknown attribute 'gtk-3-themes' for interface 'gsettings' (plugs) lint-snap-v2_plugs_attributes (gsettings, gtk-3-themes)
unknown attribute 'sound-themes' for interface 'gsettings' (plugs) lint-snap-v2_plugs_attributes (gsettings, sound-themes)
unknown attribute 'icon-themes' for interface 'gsettings' (plugs) lint-snap-v2_plugs_attributes (gsettings, icon-themes)
```

**Comment by keshavbhatt** [comment]
I added the wrong space there, sorry. Wait for new improved PR.

**Pull request merged**
