### PR TITLE
Fix selected items foreground color on dark theme

### PR DESCRIPTION
**Pull request by uninhm**

### CODE REVIEW

**Comment by kraxarn** [comment]
Thanks, noticed this as well, but didn't get the time to fix it.
I did notice the settings don't quite work though. Selecting an item makes the icon disappear (same happens with the play icon in the tracks list):
image

And the text in the list uses the normal text color by default, unless a dropdown item is selected, which looks odd. Maybe better to just always use the default text color in this case?
image
Notice how the text is a bit brighter now, probably using #ffffff instead of #f5f5f5:
image

Also, noticed that the dropdowns don't work either:
image

**Comment by uninhm** [comment]
How to enable dev mode? Now the dark theme is the older.

**Comment by uninhm** [comment]
@kraxarn test that commit please

**Comment by uninhm** [comment]
And, what do you think about this:  
`$highlight-color: #0d6954;`  
Or this:  
`$highlight-color: #0d6934;`

**Comment by kraxarn** [comment]
Only the issue of items in the dropdowns disappearing when being hovered over seems to be fixed, the other issues are still present.

The colors are primarily meant to be the same as the ones in the official client, or at least as seen in [the web player](https://open.spotify.com) as I currently don't have the actual client installed. I think most of the colors are fine for now, but they may be changed once the new theme is fully implemented and everything works as expected.

**Comment by uninhm** [comment]
> Only the issue of items in the dropdowns disappearing when being hovered over seems to be fixed, the other issues are still present.

In my case all issues are solved...

**Comment by uninhm** [comment]
image
image

The evidence

**Comment by kraxarn** [comment]
Probably safe to merge this then and i can try to troubleshoot the remaining issues later 😊

**Comment by kraxarn** [comment]
Merging this as-is for now, and leave the new dark theme behind developer mode until the other issues are resolved.

**Pull request merged**
