### PR TITLE
Fix minimize button on systems with buggy Qt windowState

### LINKED ISSUE #103: Minimize button works the first time but not thereafter
### System information

```
ABI: x86_64-little_endian-lp64
App version: v3.6-dev (678c408d) - lib v0.4
Current desktop: KDE
D-Bus support: Yes
Device: tail-bot (Computer)
Kernel: linux 5.11.16-arch1-1
Product: Arch Linux
Qt version: 5.15.2
```

### Detailed information

Since I updated to a version with the integrated top bar that has window controls and also media controls, it seems that I can minimize spotify-qt once with the menu bar item, then when I bring it back up from my KDE bottom bar, when I press the minimize button on the window again,  it won't minimize the window until the app is restarted. 

It also seems to happen if I do the first minimization by right clicking the top bar and selecting minimize: after the first time, neither the right click menu option nor the minimize control on the top right will minimize the window. I can minimize the window by clicking on the icon in the KDE bottom bar as many times as I'd like. Interestingly, if I start the app, then minimize the window and restore it by clicking the KDE bar twice, the minimize button on the window will work once before failing again until the app is relaunched like in the other scenarios.

### PR DESCRIPTION
**Pull request by lf-**
This also maintains maximize state across minimizes.

Fixes #103

### CODE REVIEW

**Review by kraxarn — COMMENTED** [review]
Would be interesting to see if the bug still occurs in Qt 6 or what is even causing it to begin with.
Either way, looks good, although, I assume minimize from the menu has the same issue (`widget/dragarea.cpp:59`), so maybe best to make a new method, like `MainWindow::minimize`.

**Comment by lf-** [comment]
Oh yeah, you're right. I'll go fix that.

Anyway, yes, the following program is broken under both qt5 and qt6 on my system.... I really think this is a qt bug, there certainly have been a lot of similar ones based on my search this morning. I should probably go file it.

```qmake
######################################################################
# Automatically generated by qmake (3.1) Thu Aug 12 13:00:40 2021
######################################################################

TEMPLATE = app
TARGET = qtbug
INCLUDEPATH += .

QT += gui widgets core

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += qtbug.cpp
```

```c++
#include <QApplication>
#include <QBoxLayout>
#include <QMainWindow>
#include <QPushButton>
#include <QTextEdit>

class Label : public QTextEdit {
public:
  Label() { startTimer(1000); }

protected:
  void timerEvent(QTimerEvent *) {
    insertPlainText("windowState: " + QString::number(window()->windowState()) + "\n");
  }
};

int main(int argc, char **argv) {
  QApplication app(argc, argv);
  auto *centralWidget = new QWidget{};
  auto *layout = new QBoxLayout{QBoxLayout::Direction::TopToBottom};
  auto *win = new QMainWindow{};

  auto *btn = new QPushButton {"Minimize me"};
  auto *label = new Label {};
  centralWidget->setLayout(layout);
  win->setCentralWidget(centralWidget);
  layout->addWidget(btn);
  layout->addWidget(label);

  btn->connect(btn, &QAbstractButton::clicked, [&win]() {
    win->setWindowState(Qt::WindowState::WindowMinimized);
  });

  win->show();

  return app.exec();
}
```

**Comment by kraxarn** [comment]
Looks good now, thanks :relaxed:
If you have Qt 6 installed, you can call cmake with `-DUSE_QT6=ON` to compile against Qt 6.

**Comment by lf-** [comment]
> Looks good now, thanks relaxed
> If you have Qt 6 installed, you can call cmake with `-DUSE_QT6=ON` to compile against Qt 6.

My repro is broken while compiling against that one too so I've filed my Qt bug accordingly :)

**Pull request merged**
